name: build react app
on:
  push:
    branches: [mohcine, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: cache
        uses: actions/cache@v4.2.0
        with:
          path: ~/.npm
          key: npm-cache-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            npm-cache-
      - name: install dependencies
        run: npm ci
      
      - name: Build Application
        run: npm run build
  
